CREATE TABLE IF NOT EXISTS players (
    name TEXT PRIMARY KEY,
    bga_id TEXT NOT NULL,
    elo REAL NOT NULL DEFAULT 1000,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS games (
     bga_id INTEGER PRIMARY KEY AUTOINCREMENT,
     name TEXT NOT NULL,
     player_id INTEGER NOT NULL,
     score REAL NOT NULL,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     FOREIGN KEY (player_id) REFERENCES players(id)
);