name: Issue assignment

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Run go test
        run: go test -v ./...
      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Run go build
        run: go build -o tmff-discord-app cmd/main.go
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 1
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: tmff-discord-app
          tag_name: ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
